### PR TITLE
:sparkles: Catmod: HTTP requests for Catnip

### PR DESCRIPTION
**Pull request by Banbury**
**Changes proposed in this pull request:**
This is a Catmod, that adds two functions for GET and POST HTTP requests. The mod is meant to be used with Catnip. In scripts one simply can use `fetch` directly.

I have added a screenshot to show, how the functions are used. But I haven't been able to display it in the README.md. Possibly the image isn't packaged correctly. At least it doesn't show in the dev tools when running the project either.

**Ping @CosmoMyzrailGorynych**

### CODE REVIEW

**Comment by CosmoMyzrailGorynych** [comment]
Please move both functions into a `requests` objects to stay in line with how other modules are made. A stylistic error: you should probably also name both blocks as `Get` and `Post` or `GET` and `POST`, right now the names differ in capitalization.

**Comment by Banbury** [comment]
I'll make the changes after the holidays.

**Comment by CosmoMyzrailGorynych** [comment]
@Banbury is it ready to be merged?

**Comment by Banbury** [comment]
I think so. But you tell me ;).

**Pull request merged**
